use_gpu: true
log_iter: 20
save_dir: output
snapshot_epoch: 1
weights: output/hrnet_w32_256x192_coco/model_final
epoch: 210
num_joints: &num_joints 17
pixel_std: &pixel_std 200
metric: KeyPointTopDownCOCOEval
num_classes: 1

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    milestones: [170, 200]
    gamma: 0.1
  - !LinearWarmup
    steps: 0

OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer:
    factor: 0.0
    type: L2

TrainDataset:
  !KeypointTopDownCocoDataset
    image_dir: train2017
    anno_path: annotations/person_keypoints_train2017.json
    dataset_dir: dataset/coco
    num_joints: *num_joints
    trainsize: [192, 256]
    pixel_std: *pixel_std
    use_gt_bbox: True


EvalDataset:
  !KeypointTopDownCocoDataset
    image_dir: val2017
    anno_path: annotations/person_keypoints_val2017.json
    dataset_dir: dataset/coco
    bbox_file: person_detection_results/COCO_val2017_detections_AP_H_56_person.json
    num_joints: *num_joints
    trainsize: [192, 256]
    pixel_std: *pixel_std
    use_gt_bbox: True
    image_thre: 0.0


TestDataset:
  !KeypointTopDownCocoDataset
    image_dir: val2017
    anno_path: annotations/person_keypoints_val2017.json
    dataset_dir: dataset/coco
    bbox_file: person_detection_results/COCO_val2017_detections_AP_H_56_person.json
    num_joints: *num_joints
    trainsize: [192, 256]
    pixel_std: *pixel_std
    use_gt_bbox: True
    image_thre: 0.0

worker_num: 0
global_mean: &global_mean [0.485, 0.456, 0.406]
global_std: &global_std [0.229, 0.224, 0.225]
TrainReader:
  sample_transforms:
    - RandomFlipScaleRotHalfBodyTrans: {scale: 0.35, rot: 45, num_joints_half_body: 8, prob_half_body: 0.3, pixel_std: *pixel_std, trainsize: [192, 256], upper_body_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], flip_pairs: [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]]}
    - InputAffine: {trainsize: [192, 256]}
    - ToHeatmapsHrnet: {hmsize: [48, 64], sigma: 2}
  batch_transforms:
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 1
  shuffle: true
  drop_last: false

EvalReader:
  sample_transforms:
    - InputAffine: {trainsize: [192, 256]}
    - ToHeatmapsHrnet: {hmsize: [48, 64], sigma: 2}
  batch_transforms:
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 16
  drop_empty: false

TestReader:
  sample_transforms:
    - InputAffine: {trainsize: [192, 256]}
    - ToHeatmapsHrnet: {hmsize: [48, 64], sigma: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 1

architecture: TopDownHrnet
pretrain_weights: Trunc_HRNet_W32_C_pretrained.pdparams

TopDownHrnet:
  backbone: HRNet
  hrnet_head: HrnetHead
  post_process: HrnetPostProcess
  flip_perm: [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]]

HRNet:
  width: &width 32
  freeze_at: -1
  freeze_norm: false
  return_idx: [0]

HrnetHead:
  num_joints: *num_joints
  width: *width
  loss: HrnetLoss

HrnetLoss:
  use_target_weight: true
